#server:
#  host: 0.0.0.0
#  port: 3000
#  domain: example.com

env:
  enviroinment: development
  logLevel: info
  name: koa-ssr
  version: 0.0.0

secret: secret

db:
  client: pg
  connection: postgres://test:test@localhost:5432/cbs
